version: '3.9'
services:
  ops:
    build:
      context: ./docker/ops
    env_file:
      - ./.env
    volumes:
      # - ${AWS_CONFIG_FILE:-~/.aws/config}:/root/.aws/config:ro
      # - ${AWS_SHARED_CREDENTIALS_FILE:-~/.aws/credentials}:/root/.aws/credentials:ro
      # - ${AZURE_CONFIG_DIR:-~/.azure}:/root/.azure
      - ${HOME}/.ssh/:/root/.ssh/:ro
      - ./.private/.ansible/:/root/.ansible/:rw
      - ./.private/.terraform.d/:/root/.terraform.d/:rw
      - ./.:/app
    working_dir: /app
