name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: version-numeric
        run: echo "::set-output name=version::$(cat VERSION.txt)"

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: v${{ steps.version-numeric.outputs.version }}

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      # https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
      # During the GitHub Container Registry beta, the only supported form of authentication is the PAT.

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/typecoercion/ops-tools:${{ steps.version-numeric.outputs.version }}
